# Generated by Django 5.0.6 on 2024-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='book',
        ),
        migrations.AddField(
            model_name='report',
            name='book_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
