# Generated by Django 5.0.6 on 2024-06-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_book_report_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='book_author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
