# Generated by Django 5.0.6 on 2024-06-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('reports', '0003_report_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
