# Generated by Django 5.0.6 on 2024-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_report_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
